base_url: "http://mgax.github.io/geo-spatial.org"
image_base_url: "https://dl.dropboxusercontent.com/u/103063/static/geospatial"
geoserver_base_url: "http://www.geo-spatial.org/geoserver"

defaults:
  - scope: {path: ""}
    values: {layout: "page"}

  - scope: {path: "", type: "articole"}
    values: {layout: "article", homepage: true}

  - scope: {path: "", type: "tutoriale"}
    values: {layout: "article", homepage: true}

  - scope: {path: "", type: "recenzii"}
    values: {layout: "article", homepage: true}

  - scope: {path: "", type: "resurse"}
    values: {layout: "article", homepage: true}

  - scope: {path: "", type: "galerii"}
    values: {layout: "article", homepage: true}

  - scope: {path: "", type: "download"}
    values: {layout: "article", homepage: true}

  - scope: {path: "", type: "osgeo"}
    values: {layout: "article", homepage: true}

  - scope: {path: "", type: "blog"}
    values: {layout: "article", homepage: true}

  - scope: {path: "", type: "info"}
    values: {layout: "article", homepage: true}

  - scope: {path: "", type: "autori"}
    values: {layout: "author"}

collections:
  articole:  {output: true, title: "Articole"}
  tutoriale: {output: true, title: "Tutoriale"}
  recenzii:  {output: true, title: "Recenzii"}
  resurse:   {output: true, title: "Resurse"}
  galerii:   {output: true, title: "Galerii"}
  download:  {output: true, title: "Download"}
  osgeo:     {output: true, title: "OSGeo"}
  blog:      {output: true, title: "Blog"}
  info:      {output: true, title: "Info"}
  stiri:     {output: true}
  autori:    {output: true}

menu: [articole, tutoriale, recenzii, resurse, galerii, download, osgeo, blog, info]

exclude:
  - 'Readme.md'
